version: 4.26.1;

networks:
  backend:
    driver: bridge

services:
  db:
    image: mysql:8.2.0
    restart: always
    container_name: db
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3307:3306
    expose:
      - 3306
    networks:
      - backend

  nest:
    container_name: nest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 123456
      DB_NAME: db
      DB_PORT: 3306
      PORT: 3000
    networks:
      - backend

  nginx: 
    image: nginx:1.25.3
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend