version: 4.26.1;
services:
  db:
    image: mysql:8.2.0
    restart: always
    container_name: db
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3307:3306
    expose:
      - 3306

  nest:
    container_name: nest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE_URL="mysql://root:123456@localhost:3306/db?schema=public"
    ports:
      - 3000:3000

  nginx: 
    image: nginx:1.25.3
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf